-- Per-task credential allowlist: which (server, account) MCP pairs a scheduled
-- task is permitted to call. NULL means "inherit global" (the prior behaviour —
-- any server in mcp_selection is permitted), so existing rows keep working
-- unchanged. A non-null (possibly empty) array enforces least-privilege: an MCP
-- call to a pair not on the list is denied before it executes.
--
-- SECURITY NOTE, and an open question that is deliberately NOT settled here:
-- credential_allowlist stores (server, account) pair NAMES only, never
-- credential values. The values do not enter the database at all — they live in
-- the process env file and are brokered host-side (internal/creds, ADR-0003,
-- ADR-0042). So this column is not a secret store.
--
-- What is unsettled is whether ACCOUNT NAMES are themselves in scope. If a
-- deployment treats them as sensitive, this column wants encryption at rest.
-- That is a threat-model decision for the repo owner, not something a migration
-- can decide, and it is recorded in SECURITY.md ("Open question: MCP account
-- names at rest") rather than here: a migration is
-- applied history, so a question parked in one is a question nobody can close in
-- place. (An earlier version of this note was an untracked security to-do that
-- pointed at a source file in an unrelated external codebase; the pointer was
-- dangling and nothing tracked the item.)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS credential_allowlist JSONB;
