import type { MetadataRoute } from "next";

import { getChatServerBase, getSharedToken } from "@/app/lib/chatServer";

// Keep installed-app labels aligned with layout.tsx's white-label metadata.
const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME?.trim() || "Fleet";

// Mirrors globals.css's own --color-bg default, so a fleet deployment with no
// client-config bundle stays self-consistent.
const DEFAULT_SPLASH = "#1a0b1e";

// Only the shapes fleet's theme renderer can emit (see colorValueRe in
// internal/httpapi/theme.go). The manifest goes to the OS, not the DOM, so an
// unexpected value is dropped rather than passed through.
const COLOR_RE = /^(?:#[0-9a-fA-F]{3,8}|(?:rgb|rgba|hsl|hsla)\([0-9a-zA-Z.,%/\s]+\))$/;

// splashColor reads the client-config bundle's dark --color-bg so an installed
// app's splash screen matches the deployment's palette instead of fleet's.
//
// It parses /theme.css rather than /client-config because this runs without a
// session and /client-config is member-gated; /theme.css is token-gated, which a
// server-side call can satisfy. That stylesheet is generated by
// renderThemeCSS, so its shape is fleet's own contract, not a third party's.
// A manifest has ONE splash color while the palette has two modes, so this takes
// the dark one — the mode fleet defaults to.
//
// Any failure (backend down, no bundle, no colors block, unparseable value)
// falls back to the built-in default: a missing splash color is cosmetic, and
// never worth failing manifest generation over.
async function splashColor(): Promise<string> {
  try {
    const res = await fetch(`${getChatServerBase()}/theme.css`, {
      headers: { "X-Chat-Server-Token": getSharedToken() },
      cache: "no-store",
    });
    if (!res.ok) return DEFAULT_SPLASH;
    const css = await res.text();
    const block = /html:root\[data-theme="dark"\]\{([^}]*)\}/.exec(css);
    if (!block) return DEFAULT_SPLASH;
    const bg = /--color-bg:\s*([^;]+);/.exec(block[1]);
    const value = bg?.[1]?.trim();
    return value && COLOR_RE.test(value) ? value : DEFAULT_SPLASH;
  } catch {
    return DEFAULT_SPLASH;
  }
}

export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const splash = await splashColor();
  return {
    name: APP_NAME,
    short_name: APP_NAME,
    start_url: "/",
    display: "standalone",
    background_color: splash,
    theme_color: splash,
    icons: [
      {
        src: "/app-icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/app-icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/app-icons/maskable-icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
